apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysqldb-atv4
  labels:
    app: mysqldb-atv4
spec:
  selector:
    matchLabels:
      app: mysqldb-atv4
  serviceName: mysql-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: mysqldb-atv4
    spec:
      containers:
        - name: mysqldb-atv4
          image: mysql:5.6
          ports:
            - containerPort: 3306
          env:
            - name: "MYSQL_ROOT_PASSWORD"
              value: admpass1
            - name: "MYSQL_DATABASE"
              value: atv4db
            - name: "MYSQL_PASSWORD"
              value: admpass1
